name: walletconnect_flutter_v2_wallet
description: An example wallet for WalletConnect v2 built with Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependency_overrides:
  win32: ^5.5.4
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  fl_toast: ^3.1.0
  qr_bar_code_scanner_dialog:
    path: packages/qr-bar-code-scanner-dialog
  get_it: ^7.2.0
  eth_sig_util: ^0.0.9
  get_it_mixin: ^4.0.0
  package_info_plus: ^7.0.0
  convert: ^3.0.1
  url_launcher: ^6.2.2
  
  # CHECK WEB SUPPORT
  kadena_dart_sdk: ^2.3.2
  solana: ^0.30.4
  polkadart_keyring: ^0.4.3
  polkadart: ^0.4.6
  walletconnect_flutter_v2: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  web3modal_flutter: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.5.3
  dependency_validator: ^3.2.2

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "./AppIcon.png" 
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/lachain_logo.png
